require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe HdfsPathsController do

  # This should return the minimal set of attributes required to create a valid
  # HdfsPath. As you add validations to HdfsPath, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all hdfs_paths as @hdfs_paths" do
      hdfs_path = HdfsPath.create! valid_attributes
      get :index
      assigns(:hdfs_paths).should eq([hdfs_path])
    end
  end

  describe "GET show" do
    it "assigns the requested hdfs_path as @hdfs_path" do
      hdfs_path = HdfsPath.create! valid_attributes
      get :show, :id => hdfs_path.id
      assigns(:hdfs_path).should eq(hdfs_path)
    end
  end

  describe "GET new" do
    it "assigns a new hdfs_path as @hdfs_path" do
      get :new
      assigns(:hdfs_path).should be_a_new(HdfsPath)
    end
  end

  describe "GET edit" do
    it "assigns the requested hdfs_path as @hdfs_path" do
      hdfs_path = HdfsPath.create! valid_attributes
      get :edit, :id => hdfs_path.id
      assigns(:hdfs_path).should eq(hdfs_path)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new HdfsPath" do
        expect {
          post :create, :hdfs_path => valid_attributes
        }.to change(HdfsPath, :count).by(1)
      end

      it "assigns a newly created hdfs_path as @hdfs_path" do
        post :create, :hdfs_path => valid_attributes
        assigns(:hdfs_path).should be_a(HdfsPath)
        assigns(:hdfs_path).should be_persisted
      end

      it "redirects to the created hdfs_path" do
        post :create, :hdfs_path => valid_attributes
        response.should redirect_to(HdfsPath.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved hdfs_path as @hdfs_path" do
        # Trigger the behavior that occurs when invalid params are submitted
        HdfsPath.any_instance.stub(:save).and_return(false)
        post :create, :hdfs_path => {}
        assigns(:hdfs_path).should be_a_new(HdfsPath)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        HdfsPath.any_instance.stub(:save).and_return(false)
        post :create, :hdfs_path => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested hdfs_path" do
        hdfs_path = HdfsPath.create! valid_attributes
        # Assuming there are no other hdfs_paths in the database, this
        # specifies that the HdfsPath created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        HdfsPath.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => hdfs_path.id, :hdfs_path => {'these' => 'params'}
      end

      it "assigns the requested hdfs_path as @hdfs_path" do
        hdfs_path = HdfsPath.create! valid_attributes
        put :update, :id => hdfs_path.id, :hdfs_path => valid_attributes
        assigns(:hdfs_path).should eq(hdfs_path)
      end

      it "redirects to the hdfs_path" do
        hdfs_path = HdfsPath.create! valid_attributes
        put :update, :id => hdfs_path.id, :hdfs_path => valid_attributes
        response.should redirect_to(hdfs_path)
      end
    end

    describe "with invalid params" do
      it "assigns the hdfs_path as @hdfs_path" do
        hdfs_path = HdfsPath.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HdfsPath.any_instance.stub(:save).and_return(false)
        put :update, :id => hdfs_path.id, :hdfs_path => {}
        assigns(:hdfs_path).should eq(hdfs_path)
      end

      it "re-renders the 'edit' template" do
        hdfs_path = HdfsPath.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        HdfsPath.any_instance.stub(:save).and_return(false)
        put :update, :id => hdfs_path.id, :hdfs_path => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested hdfs_path" do
      hdfs_path = HdfsPath.create! valid_attributes
      expect {
        delete :destroy, :id => hdfs_path.id
      }.to change(HdfsPath, :count).by(-1)
    end

    it "redirects to the hdfs_paths list" do
      hdfs_path = HdfsPath.create! valid_attributes
      delete :destroy, :id => hdfs_path.id
      response.should redirect_to(hdfs_paths_url)
    end
  end

end
