require 'spec_helper'

# This spec was generated by rspec-rails when you ran the scaffold generator.
# It demonstrates how one might use RSpec to specify the controller code that
# was generated by Rails when you ran the scaffold generator.
#
# It assumes that the implementation code is generated by the rails scaffold
# generator.  If you are using any extension libraries to generate different
# controller code, this generated spec may or may not pass.
#
# It only uses APIs available in rails and/or rspec-rails.  There are a number
# of tools you can use to make these specs even more expressive, but we're
# sticking to rails and rspec-rails APIs to keep things simple and stable.
#
# Compared to earlier versions of this generator, there is very limited use of
# stubs and message expectations in this spec.  Stubs are only used when there
# is no simpler way to get a handle on the object needed for the example.
# Message expectations are only used when there is no simpler way to specify
# that an instance is receiving a specific message.

describe SolrServersController do

  # This should return the minimal set of attributes required to create a valid
  # SolrServer. As you add validations to SolrServer, be sure to
  # update the return value of this method accordingly.
  def valid_attributes
    {}
  end

  describe "GET index" do
    it "assigns all solr_servers as @solr_servers" do
      solr_server = SolrServer.create! valid_attributes
      get :index
      assigns(:solr_servers).should eq([solr_server])
    end
  end

  describe "GET show" do
    it "assigns the requested solr_server as @solr_server" do
      solr_server = SolrServer.create! valid_attributes
      get :show, :id => solr_server.id
      assigns(:solr_server).should eq(solr_server)
    end
  end

  describe "GET new" do
    it "assigns a new solr_server as @solr_server" do
      get :new
      assigns(:solr_server).should be_a_new(SolrServer)
    end
  end

  describe "GET edit" do
    it "assigns the requested solr_server as @solr_server" do
      solr_server = SolrServer.create! valid_attributes
      get :edit, :id => solr_server.id
      assigns(:solr_server).should eq(solr_server)
    end
  end

  describe "POST create" do
    describe "with valid params" do
      it "creates a new SolrServer" do
        expect {
          post :create, :solr_server => valid_attributes
        }.to change(SolrServer, :count).by(1)
      end

      it "assigns a newly created solr_server as @solr_server" do
        post :create, :solr_server => valid_attributes
        assigns(:solr_server).should be_a(SolrServer)
        assigns(:solr_server).should be_persisted
      end

      it "redirects to the created solr_server" do
        post :create, :solr_server => valid_attributes
        response.should redirect_to(SolrServer.last)
      end
    end

    describe "with invalid params" do
      it "assigns a newly created but unsaved solr_server as @solr_server" do
        # Trigger the behavior that occurs when invalid params are submitted
        SolrServer.any_instance.stub(:save).and_return(false)
        post :create, :solr_server => {}
        assigns(:solr_server).should be_a_new(SolrServer)
      end

      it "re-renders the 'new' template" do
        # Trigger the behavior that occurs when invalid params are submitted
        SolrServer.any_instance.stub(:save).and_return(false)
        post :create, :solr_server => {}
        response.should render_template("new")
      end
    end
  end

  describe "PUT update" do
    describe "with valid params" do
      it "updates the requested solr_server" do
        solr_server = SolrServer.create! valid_attributes
        # Assuming there are no other solr_servers in the database, this
        # specifies that the SolrServer created on the previous line
        # receives the :update_attributes message with whatever params are
        # submitted in the request.
        SolrServer.any_instance.should_receive(:update_attributes).with({'these' => 'params'})
        put :update, :id => solr_server.id, :solr_server => {'these' => 'params'}
      end

      it "assigns the requested solr_server as @solr_server" do
        solr_server = SolrServer.create! valid_attributes
        put :update, :id => solr_server.id, :solr_server => valid_attributes
        assigns(:solr_server).should eq(solr_server)
      end

      it "redirects to the solr_server" do
        solr_server = SolrServer.create! valid_attributes
        put :update, :id => solr_server.id, :solr_server => valid_attributes
        response.should redirect_to(solr_server)
      end
    end

    describe "with invalid params" do
      it "assigns the solr_server as @solr_server" do
        solr_server = SolrServer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SolrServer.any_instance.stub(:save).and_return(false)
        put :update, :id => solr_server.id, :solr_server => {}
        assigns(:solr_server).should eq(solr_server)
      end

      it "re-renders the 'edit' template" do
        solr_server = SolrServer.create! valid_attributes
        # Trigger the behavior that occurs when invalid params are submitted
        SolrServer.any_instance.stub(:save).and_return(false)
        put :update, :id => solr_server.id, :solr_server => {}
        response.should render_template("edit")
      end
    end
  end

  describe "DELETE destroy" do
    it "destroys the requested solr_server" do
      solr_server = SolrServer.create! valid_attributes
      expect {
        delete :destroy, :id => solr_server.id
      }.to change(SolrServer, :count).by(-1)
    end

    it "redirects to the solr_servers list" do
      solr_server = SolrServer.create! valid_attributes
      delete :destroy, :id => solr_server.id
      response.should redirect_to(solr_servers_url)
    end
  end

end
